# Site settings
title: Jekyll Boilerplate
email: purvisbilly@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Getting on the web is easy, but it's even easier with Jekyll-Boilerplate. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: mrmonkeytech
github_username:  BillyPuris

# Build settings
markdown: kramdown

# Excludes
exclude: [node_modules]
